### PR TITLE
added ecoli model from Lapierre et al

### PR DESCRIPTION
**Pull request by fbaumdicker**
I added a simple constant model for the evolution of Escherichia coli as described in Lapierre et al, MBE, 2016. Lapierre also considers models with gene conversion and selection which is so far not included.
The evolutionary rates have been taken from Table 2 in Lapierre et al.
In the example file, a sample of size 100 is generated.
At the moment this takes less than a minute. This will increase when gene conversion is included.

### CODE REVIEW

**Comment by fbaumdicker** [comment]
I started today and hope to have the python version running within the next 2-3 weeks.

**Comment by fbaumdicker** [comment]
Here is the clickable link to the original publication, which I used to infer the parameters:

[(https://doi.org/10.1093/molbev/msw048)]

I also added the link to the e_coli.py file.

**Comment by jeromekelleher** [comment]
Looks good, thanks @fbaumdicker. Can you [rebase and squash](https://stdpopsim.readthedocs.io/en/latest/development.html) please?

@andrewkern, my take would be to merge this and see how it fits in with the bigger picture later. What do you think?

**Comment by andrewkern** [comment]
sounds good to me. @fbaumdicker after the rebase let's merge.

**Comment by fbaumdicker** [comment]
Ok, I rebased and squashed. @jeromekelleher Hope this is fine? Next time I will also use a separate branch instead of master.

**Comment by jeromekelleher** [comment]
Perfect, thanks @fbaumdicker!

**Pull request merged**
