### PR TITLE
Pongo documentation and QC

### LINKED ISSUE #213: Pongo QC
The orangutan model needs documentation, and I think there is an issue with the migration rate units.

### PR DESCRIPTION
**Pull request by apragsdale**
Closes #213.

Added documentation and genome information for the Pongo model. I also included some QC code for it here. Since I also changed the original model (needed to fix the migration rate), it might be worth having an extra set of eyes to avoid me possibly duplicating an error between the original and qc model.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Nice, thanks @apragsdale! @ndukler, @andrewkern, can you have a quick look through this please?

**Comment by jeromekelleher** [comment]
I think your email address isn't correctly setup @apragsdale, so your commits won't be correctly attributed to you. You probably need to make sure that your local git email address matches up with your github one.

**Comment by jeromekelleher** [comment]
If you fix this and rebase this PR, it should sort it self out.

**Comment by apragsdale** [comment]
> I think your email address isn't correctly setup @apragsdale, so your commits won't be correctly attributed to you. You probably need to make sure that your local git email address matches up with your github one.

Huh, interesting. Yeah it was still on my old account. I suppose my previous commits will remain attributed to my last email account.. is that a problem? It's updated now in any case.

**Comment by jeromekelleher** [comment]
> Huh, interesting. Yeah it was still on my old account. I suppose my previous commits will remain attributed to my last email account.. is that a problem? It's updated now in any case.

Yeah, your previous commits won't be associated with the right account unfortunately, and we can't really change that now. It's only a problem in that you won't get the correct GitHub Kudos for your contributions up to this point.

**Comment by apragsdale** [comment]
This should be good to merge as well then, unless you need me to rebase to account for other pull requests?

**Comment by jeromekelleher** [comment]
It would be good to rebase to get this pointing at the tip of master, if you don't mind please.

**Comment by apragsdale** [comment]
Ok, rebased.

**Pull request merged**
