### PR TITLE
added generation time to homo_sap, Arab, and dros

### PR DESCRIPTION
**Pull request by jgallowa07**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM; can we get some references backing these up? This is probably the sort of thing we want to make Citeable later, so it'd be great to get a reference into the comments for now.

**Comment by andrewkern** [comment]
i will find some appropriate citations

**Comment by andrewkern** [comment]
one bit of weirdness here-- some of the models have their own generation time assumptions built in-- for instance the Li and Stephan model for Drosophila. What should we do in these cases team?

**Comment by jeromekelleher** [comment]
> one bit of weirdness here-- some of the models have their own generation time assumptions built in-- for instance the Li and Stephan model for Drosophila. What should we do in these cases team?

Weirdness is inevitable I guess - we'll just have to document the assumptions as well as we can.

**Comment by andrewkern** [comment]
superseding this PR with [this one](https://github.com/popgensims/stdpopsim/pull/92)

**Pull request closed without merging**
