### PR TITLE
Addend H. sapiens archaic model

### PR DESCRIPTION
**Pull request by apragsdale**
Added Ragsdale & Gravel archaic model (https://doi.org/10.1371/journal.pgen.1008204).

### CODE REVIEW

**Comment by ndukler** [comment]
Thanks for this @apragsdale ! @andrewkern or @jeromekelleher  can you please merge this in so I can get the QC up ASAP?

**Comment by jeromekelleher** [comment]
Done - thanks @apragsdale and @ndukler!

**Comment by ndukler** [comment]
Awesome! I'll try to have the QC and documentation up by the end of the day.

**Comment by ndukler** [comment]
Ah, I see you already did the documentation, thanks!

**Comment by apragsdale** [comment]
Let me know if there are other things I should do for the model and integration into the repo - I'm not entirely sure if more is needed from me, or just waiting for independent implementation and comparison. Thanks!! (still getting the hang of the work flow for this)

**Pull request merged**
