### PR TITLE
Parameter tables for the remaining models and warning when they are missing

### PR DESCRIPTION
**Pull request by noscode**
I have added parameters for models:
- Zigzag_1S14
- AncientEurasia_9K19
- SouthMiddleAtlas_1D17
- African2Epoch_1H18

Also I have fixed `speciescatalog.py` to emit warning.

I am not sure for SouthMiddleAtlas_1D17 as I have not found table in the paper, it is based on the code. Also there is no common notation among tables, for example in my tables I used `Time`, but I saw something like `Epoch time` and `ADMIX time` in other places. May be we want to discuss it?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Fantastic, thanks @noscode! You're right we should standardise the notation in the tables --- let's open an issue to discuss once we've merged this PR.

The SouthMiddleAtlas_1D17 is problematic, because we're not actually using all the values in the arrays I think (just the first 8 I think? It's in the code anyway). Can you update the table to just output the values we're using please? (We should also just remove the stuff we're not using, it's confusing to have it in there, but that should probably be done in another PR where we document the model properly also.)

Can we get some reviewers to check the values here also please?

**Comment by noscode** [comment]
I have looked to the code for SouthMiddleAtlas_1D17. As I see from lines 105-117 all values are used. There are some comments like that:
    # MSMC is accurate from 40Kya-1.6Mya for A.thaliana (Durvasula et al 2017)
    # set the first 7 sizes
    # equal to the size at 8 (~40Kya)

    # set the last 2 entries equal
    # to the size at 30 (~1.6Mya)

I have take them into account while I was filling the table, so it seems there are less values but still a lot.

**Comment by noscode** [comment]
Reviews will be appreciated!

**Comment by jeromekelleher** [comment]
> these look good to me, one question though--- why did you end up uncommenting the logger.warning call in speciescatalog.py?

This is so we raise a warning when generating the docs if the model table is missing, and CI will therefore fail.

**Comment by jeromekelleher** [comment]
Can you rebase this please @noscode? I think there's some updates needed also.

**Comment by noscode** [comment]
I have rebased, please, check it.

**Comment by jeromekelleher** [comment]
Perfect, thanks @noscode!

**Pull request merged**
