### PR TITLE
Fix browning admixed population

### PR DESCRIPTION
**Pull request by ndukler**
Fixes issue #185

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM. @apragsdale, do you agree with this?

**Comment by apragsdale** [comment]
Yeah, it looks good to me.

I did just notice a typo in the description, where it is supposed to say "and 1/2 Asian" but has a line break (lines 419-420). Easy to add that fix to this pr?

**Comment by ndukler** [comment]
> Yeah, it looks good to me.
> 
> I did just notice a typo in the description, where it is supposed to say "and 1/2 Asian" but has a line break (lines 419-420). Easy to add that fix to this pr?

Fixed

**Comment by jeromekelleher** [comment]
Great, thanks both. Merging.

**Comment by ndukler** [comment]
Closes #185

**Pull request merged**
