### PR TITLE
QC for A. Thaliana Durvasula2017MSMC

### PR DESCRIPTION
**Pull request by Chris1221**
I've implemented the QC requested in issue #97 for the Durvasula demographic model of A. Thaliana history. Overall I had no issue with how it was implemented and agreed with the author's decisions, chiefly to mask the first 8 epochs and the last 2, due to the limitations of MSMC as discussed in the referenced article. My only minor point of contention was the decision to round all the values, presumably for readability. I'm not sure if this was completely necessary, and it might be more reproducible to simple copy-paste the MSMC output (which is presented in the chat log in #97) rather than rounding it as both Arun and now myself have done. However, I don't think it's a major issue, and am happy to go forward as is. I've included the QC model in the test suite, and run it with no problem. 

Let me know if there's anything else that needs to be done here.

### CODE REVIEW

**Comment by andrewkern** [comment]
just assigned @ndukler to review this QC PR.... should be good I believe.

**Comment by jeromekelleher** [comment]
Yep, LGTM too.

**Comment by andrewkern** [comment]
hey @ndukler- just pinging you on this PR. any chance you can review before we merge? ignore me if you are on vacation somewhere!

**Comment by ndukler** [comment]
Sorry @andrewkern , I'll look it over by the end of the day.

**Comment by andrewkern** [comment]
thanks @ndukler! going to merge this in

**Pull request merged**
