### PR TITLE
Add help for genetic maps

### PR DESCRIPTION
**Pull request by apragsdale**
Addressing #130 to add `--help-genetic-maps` option. I tried to closely follow the approach for displaying help with models.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Great stuff, thanks @apragsdale! Looks good to me. One minor quibble. When we run ``stdpopsim --help`` we get:
```
optional arguments:
  -h, --help            show this help message and exit
  --help-models [HELP_MODELS]
                        Print descriptions of simulation models and exit. If a
                        model ID is provided as an argument show help for this
                        model; otherwise show help for all available models
  -q, --quiet           Do not write out citation information
  --help-genetic-maps [HELP_GENETIC_MAPS]
                        Print list of genetic maps and exit. If a genetic map
                        ID is given as an argument, show help for this map.
                        Otherwise show help for all available genetic maps
```

It probably makes sense to have ``--help-models`` and ``--help-genetic-maps`` together. Maybe we should move ``--quiet`` up the list so that these two are adjacent?

**Comment by apragsdale** [comment]
That makes a lot of sense, and is an easy change to make. I'll update and re-push this afternoon.

**Comment by apragsdale** [comment]
Ok, pushed a change - I moved `--help-genetic-maps` up so that the help options are all grouped together. For example, if I run `stdpopsim homsap --help`, I now get:
```
optional arguments:
  -h, --help            show this help message and exit
  --help-models [HELP_MODELS]
                        Print descriptions of simulation models and exit. If a
                        model ID is provided as an argument show help for this
                        model; otherwise show help for all available models
  --help-genetic-maps [HELP_GENETIC_MAPS]
                        Print list of genetic maps and exit. If a genetic map
                        ID is given as an argument, show help for this map.
                        Otherwise show help for all available genetic maps
  -q, --quiet           Do not write out citation information
  -g , --genetic-map    Specify a particular genetic map. If no genetic map is
                        specified use a flat map by default. Available maps:
                        HapmapII_GRCh37, Decode_2010_sex_averaged.
```
and so on.

**Comment by ndukler** [comment]
Once this gets pulled I will add a ``--help-defaults`` option so that people can see the default population size and generation time for the species (and citations). I realized I couldn't find an easy way for people to see it from the CLI when I was writing the tutorial.

**Comment by jeromekelleher** [comment]
Excellent idea @ndukler; I've opened #168 to track.

Thanks @apragsdale, this is an excellent addition!

**Pull request merged**
