### PR TITLE
CLI for running simulations

### PR DESCRIPTION
**Pull request by jeromekelleher**
@reedacartwright made the point that it would be very helpful for people who have no Python knowledge to be able to run standard simulations. So, I thought it might be a good idea to add a command line interface to stdpopsim which would enable this. Here's a very rough first outline for discussion.

When installed, this would be invoked either via ``stdpopsim`` or ``python3 -m stdpopsim``.

The idea is to use hierarchical subcommands for species/models. So, on the top level we currently have:
```
$ python3 -m stdpopsim --help
usage: __main__.py [-h] [-V] [-v]
                   {homo-sapiens,arabadopsis-thaliana,e-coli} ...

Run simulations defined by stdpopsim from the command line

positional arguments:
  {homo-sapiens,arabadopsis-thaliana,e-coli}
    homo-sapiens        Run simulations of human history.
    arabadopsis-thaliana
                        Run simulations of Arabadopsis thaliana.
    e-coli              Run simulations of E-coli.

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit
  -v, --verbosity       Increase the verbosity
```

Then, for homo-sapiens, we have further subcommands that define the model:
```
$ python3 -m stdpopsim homo-sapiens --help
usage: __main__.py homo-sapiens [-h] [-g {HapmapII_GRCh37}] [-c CHROMOSOME]
                                {GutenkunstThreePopOutOfAfrica,TennessenEuropean}
                                ...

positional arguments:
  {GutenkunstThreePopOutOfAfrica,TennessenEuropean}
    GutenkunstThreePopOutOfAfrica
                        Runs the three population out-of-Africa model
    TennessenEuropean   Runs the TennessenEuropean model.

optional arguments:
  -h, --help            show this help message and exit
  -g {HapmapII_GRCh37}, --genetic-map {HapmapII_GRCh37}
                        Specify a particular genetic map. Use a flat map by
                        default.
  -c CHROMOSOME, --chromosome CHROMOSOME
                        Simulate a specific chromosome
```
We've defined two population models here, and also allowed the user to specify a genetic map and chromosome (if they want).

Finally, GutenkunstThreePopOutOfAfrica allows us fill in the parameters of the actual model.
```
$ python3 -m stdpopsim homo-sapiens GutenkunstThreePopOutOfAfrica --help
usage: __main__.py homo-sapiens GutenkunstThreePopOutOfAfrica
       [-h] [--num-yri-samples NUM_YRI_SAMPLES]
       [--num-ceu-samples NUM_CEU_SAMPLES] [--num-chb-samples NUM_CHB_SAMPLES]
       output

positional arguments:
  output                The file to write simulated tree sequence to

optional arguments:
  -h, --help            show this help message and exit
  --num-yri-samples NUM_YRI_SAMPLES
                        The number of samples to take from the YRI population
  --num-ceu-samples NUM_CEU_SAMPLES
                        The number of samples to take from the CEU population
  --num-chb-samples NUM_CHB_SAMPLES
                        The number of samples to take from the CHB population
```

Running this with verbosity turned on then, we might see
```
$ python3 -m stdpopsim -vv homo-sapiens -c chr20 GutenkunstThreePopOutOfAfrica out.trees --num-yri-samples=10

2019-03-26 20:34:13,238 [16329] INFO     stdpopsim.cli: Using flat genetic map
2019-03-26 20:34:13,238 [16329] INFO     stdpopsim.cli: Running GutenkunstThreePopOutOfAfrica with YRI=10 CEU=0 CHB=0
```

This is a rough initial outline, and I think it's fairly clear where it would go from here. It would be a good bit of work, but I think probably worth it.

Any thoughts?

### CODE REVIEW

**Comment by reedacartwright** [comment]
Thanks, @jeromekelleher, for putting this prototype together so quickly. It looks very usable.  I've been thinking about how to seed the random number generator with reproducibility in mind, and this is what I've come up with.

1. Default to a high-quality random seed
2. Allow users to specify a seed
3. Provide an option, say `--reproducable-seed`, that uses a seed saved in the program.
    - For extra credit, hash the special seed with the command line options to decouple simulations that have different options.

**Comment by reedacartwright** [comment]
Question about the CLI: Is it better (in the long term) to put the simulation code in cli.py, or have that in the specific simulation modules (perhaps as a common interface)? That way when someone implements a new model, they don't have to update cli.py.

Of course separation might be important because there could be a reason why we don't want to expose a CLI for specific in-development models.

Is it useful to have a unit-test or QC report that will notify if a new model doesn't have corresponding CLI access?

**Comment by jeromekelleher** [comment]
> Thanks, @jeromekelleher, for putting this prototype together so quickly. It looks very usable. I've been thinking about how to seed the random number generator with reproducibility in mind, and this is what I've come up with.

Awesome! In terms of seeds, we definitely need a CLI option to specify, but otherwise I think we're covered. Msprime generates a sensible seed by default (using /dev/urandom, if available, IIRC), and the seed is recorded in the output tree sequence:
```
$ msp simulate 10 tmp.trees
$ python3 -m tskit provenances tmp.trees | tail -n 1 | cut -f 3 | jq
{
  "environment": {
    "libraries": {
      "kastore": {
        "version": "0.1.0"
      },
      "gsl": {
        "version": "2.4"
      }
    },
    "python": {
      "implementation": "CPython",
      "version": "2.7.15rc1"
    },
    "os": {
      "node": "empire",
      "release": "4.15.0-46-generic",
      "machine": "x86_64",
      "version": "#49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019",
      "system": "Linux"
    }
  },
  "parameters": {
    "TODO": "add other simulation parameters",
    "random_seed": 3146508678,
    "command": "simulate"
  },
  "schema_version": "1.0.0",
  "software": {
    "version": "0.6.2",
    "name": "msprime"
  }
}
```

The seed is recorded in there, and ultimately all the other parameters will be too (if/when I ever get time to sort it out...)

**Comment by jeromekelleher** [comment]
> Question about the CLI: Is it better (in the long term) to put the simulation code in cli.py, or have that in the specific simulation modules (perhaps as a common interface)? That way when someone implements a new model, they don't have to update cli.py.

I like keeping the code for running the simulations within the ``cli`` module because we can then tightly couple it with the command line interface. For example, in the current code, we're able to exit with a meaningful error message directly when the user gives in bad input. OK, we could raise exceptions from another module, but then we'd have to catch them and then format the output to give a decent message. Also, we can just pass the ``args`` value in directly; if we had the running code in a separate module we'd have to unpack these again into keyword arguments, etc. It just comes down to a lot of boilerplate for no real advantage IMO.

Also, I think it would be very difficult to make a generic CLI->model running interface. Creating the samples is going to be quite specific, and it's a lot easier to just do this directly where the model is defined, I think.

> Is it useful to have a unit-test or QC report that will notify if a new model doesn't have corresponding CLI access?

We can probably track this as part of the review process I'd imagine.

**Comment by reedacartwright** [comment]
@jeromekelleher. That all makes sense. (And bonus points for using `jq`.)

**Comment by jeromekelleher** [comment]
I've updated this with some decent improvements:

1. Partial refactor of the genome code to allow cleaner access to genetic maps, etc. (will open an issue to discuss this)
2. Reproducibility via by storing the input command line (and environment information) in the output tree sequence provenance table.

**Comment by reedacartwright** [comment]
For specifying population sizes can we make the interface generic like -n ceu=10 or -n yri,5 ?

Can the current --num-xxx be used to populate a dictionary of populations and sizes without hardcoding each option?

**Comment by jeromekelleher** [comment]
> For specifying population sizes can we make the interface generic like -n ceu=10 or -n yri,5 ?

Sure, we could do that. The downside is that we lose the automatic help text generation:

```
$ python3 -m stdpopsim homo-sapiens GutenkunstThreePopOutOfAfrica --help
usage: __main__.py homo-sapiens GutenkunstThreePopOutOfAfrica
       [-h] [--num-yri-samples NUM_YRI_SAMPLES]
       [--num-ceu-samples NUM_CEU_SAMPLES] [--num-chb-samples NUM_CHB_SAMPLES]
       output

positional arguments:
  output                The file to write simulated tree sequence to

optional arguments:
  -h, --help            show this help message and exit
  --num-yri-samples NUM_YRI_SAMPLES
                        The number of samples to take from the YRI population
  --num-ceu-samples NUM_CEU_SAMPLES
                        The number of samples to take from the CEU population
  --num-chb-samples NUM_CHB_SAMPLES
                        The number of samples to take from the CHB population
```

> Can the current --num-xxx be used to populate a dictionary of populations and sizes without hardcoding each option?

We could definitely add a generic layer here, which would certainly be easier to program with. I'm not sure it would be better for the user though.

**Comment by reedacartwright** [comment]
Is it possible to take a dictionary of population names and populate the command line options automatically?

**Comment by jeromekelleher** [comment]
> Is it possible to take a dictionary of population names and populate the command line options automatically?

Yes, almost certainly. Good idea.

**Comment by jeromekelleher** [comment]
I've done a bit more work on this, and I'd like to merge it as a WIP so we can get people playing with it and get some ideas on how to improve it. In particular, if we agree on the basic functionality, I'd like to move on to refactoring the genome/chromosome/recombination map/mutation map stuff which has been half-done here, before cycling back to finish up the CLI itself. There's more discussion in the comments of where I've cut corners here in order to get something basically working, and ideas for how to make it more streamlined.

Pinging @petrelharp, @carjed, @andrewkern for review here.

**Comment by andrewkern** [comment]
first, the citation stuff you have added here is brilliant- that will help a lot along the way.

second, i think the CLI is clunky to use now, mostly because of the specifics of all the subparsers. let's merge it now and work on it as time allows. i'd be curious to get @reedacartwright's take on the UIX too.

**Comment by reedacartwright** [comment]
I was planning to try to learn Python and put some work into the CLI
because I have opinions.  But I'm currently focused on something else....

**Comment by jeromekelleher** [comment]
> I was planning to try to learn Python and put some work into the CLI because I have opinions.  But I'm currently focused on something else....

Yeah, I got the feeling you were otherwise occupied @reedacartwright. Perhaps a little Python hacking would be a welcome distraction? Once this is merged it should be straightforward to play around with the CLI a bit and we can hopefully figure out a UI that's more pleasing...

**Comment by jeromekelleher** [comment]
OK, I'm going to merge this. Will send out some instructions on how to use it on the mailing list.

**Pull request merged**
